title:              TCP Plumber
email:              kedar.t.bhatia@gmail.com
description:        "Knowledge is power"

author:             Kedar Bhatia
#baseurl:            ""
url:                "https://ktbhatia.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    KTBhatia
#facebook_username:  StartBootstrap
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

remote_theme: pages-themes/modernist@v0.2.0

plugins:
  - jekyll-seo-tag  # Required for this theme
  - jekyll-remote-theme  # Ensures remote themes load on GitHub Pages
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  
console:
  style: hacker              # Neon green-on-black terminal (case-sensitive!)
  listen_for_clients_preferred_style: false  # Forces hacker style (ignores OS dark mode)

header_pages:                # Required for navigation & full theme load
  - index.md
  - about.md

show_hero_on_post: false     # Removes big grey banner from posts (brings content up)
