title:              TCP Plumber
email:              kedar.t.bhatia@gmail.com
description:        "Knowledge is power"

author:             Kedar Bhatia
#baseurl:            ""
url:                "https://ktbhatia.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    KTBhatia
#facebook_username:  StartBootstrap
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-seo-tag  # Required for this theme
  - jekyll-remote-theme  # Ensures remote themes load on GitHub Pages
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
remote_theme: b2a3e8/jekyll-theme-console
style: hacker          # ← green-on-black terminal glory
show_hero: true
hero_subtitle: "F5 • Linux • Automation • Bash"
