title:              TCP Plumber
email:              kedar.t.bhatia@gmail.com
description:        "Knowledge is power"

author:             Kedar Bhatia
#baseurl:            ""
url:                "https://ktbhatia.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    KTBhatia
#facebook_username:  StartBootstrap
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-seo-tag  # Required for this theme
  - jekyll-remote-theme  # Ensures remote themes load on GitHub Pages
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
remote_theme: b2a3e8/jekyll-theme-console
console:
  style: hacker                 # forces green-on-black terminal
  listen_for_clients_preferred_style: false   # disables OS dark-mode override
show_hero_on_post: false        # removes huge grey banner from posts (you wanted this)
